### ISSUE TITLE
Error when using standalone player?

### ISSUE THREAD

**Issue by AFWSI** [UPBGE/upbge#1163]
What is this ```Error: totblock: 122```  when using the standalone player? I have also noticed this like 4 months ago.
```
Info: Total files 0 | Changed 0 | Failed 0
found bundled python: C:\upbge-git\build_windows_Full_x64_vc15_Release\bin\Release\2.83\python
Exception in module register(): C:\upbge-git\build_windows_Full_x64_vc15_Release\bin\Release\2.83\scripts\addons\cycles\__init__.py
Traceback (most recent call last):
  File "C:\upbge-git\build_windows_Full_x64_vc15_Release\bin\Release\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\upbge-git\build_windows_Full_x64_vc15_Release\bin\Release\2.83\scripts\addons\cycles\__init__.py", line 124, in register
    from . import properties
  File "C:\upbge-git\build_windows_Full_x64_vc15_Release\bin\Release\2.83\scripts\addons\cycles\properties.py", line 34, in <module>
    import _cycles
ModuleNotFoundError: No module named '_cycles'
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GTX 950M/PCIe/SSE2
GL_VERSION: 4.5.0 NVIDIA 445.75
GL_SHADING_LANGUAGE_VERSION: 4.50 NVIDIA
Supported Extensions...
 GL_ARB_shader_objects supported?       yes.
 GL_ARB_geometry_shader4 supported?     yes.
 GL_ARB_vertex_shader supported?        yes.
 ----------Details----------
  Max uniform components.4096
  Max varying floats.124
  Max vertex texture units.32
  Max vertex attribs.16
  Max combined texture units.192

 GL_ARB_fragment_shader supported?      yes.
 ----------Details----------
  Max uniform components.4096

 GL_ARB_texture_cube_map supported?     yes.
 ----------Details----------
  Max cubemap size.16384

 GL_ARB_multitexture supported?         yes.
 ----------Details----------
  Max texture units available.  4

 GL_ARB_texture_env_combine supported?  yes.
 GL_ARB_draw_instanced supported?  yes.
Error: totblock: 122
```

**Comment by youle31** [comment]
This is a message to warn developers that few things are not freed at standalone exit but 122 is very small compared to the 5000000 that there were some time ago. You don't have to care about that.
