### ISSUE TITLE
`AttributeError` happens during startup

### ISSUE THREAD

**Issue by Mo-Dabao** [UPBGE/upbge#1838]
Win11 22H2

upbge-0.36.1-windows-x86_64.7z

It always complains as follow during startup, and the cmd window stays open.

```
Read prefs: "D:\upbge-0.36.1\3.6\config\userpref.blend"
Traceback (most recent call last):
  File "D:\upbge-0.36.1\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "D:\upbge-0.36.1\3.6\scripts\addons\pose_library\__init__.py", line 24, in <module>
    from . import gui, keymaps, operators, conversion
  File "D:\upbge-0.36.1\3.6\scripts\addons\pose_library\gui.py", line 33, in <module>
    class VIEW3D_AST_pose_library(bpy.types.AssetShelf):
AttributeError: 'module' object has no attribute 'AssetShelf'
```

upbge-0.36-windows-x86_64.7z doesn't complain, while the cmd window stays open too.

**Comment by youle31** [comment]
Thanks for report, I close it as it is similar to this one https://github.com/UPBGE/upbge/issues/1840
