### ISSUE TITLE
Program crashed when i press p / error code: "EXCEPTION_ACCESS_VIOLATION" 

### ISSUE THREAD

**Issue by Umuttkrc** [UPBGE/upbge#1843]
When i press p upbge is crashed. I can't fix or find the problem. Also, i'm trying to add some add-ons and active them but when i'm close the program these add ons deactived automatically.

Here is my crash reports. I try to select none to my audio settings. Try to install unistall, but nothing changes.

Traceback (most recent call last):
  File "C:\Blender Game Engine\upbge-0.36.1-windows-x86_64\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Blender Game Engine\upbge-0.36.1-windows-x86_64\3.6\scripts\addons\pose_library\__init__.py", line 24, in <module>
    from . import gui, keymaps, operators, conversion
  File "C:\Blender Game Engine\upbge-0.36.1-windows-x86_64\3.6\scripts\addons\pose_library\gui.py", line 33, in <module>
    class VIEW3D_AST_pose_library(bpy.types.AssetShelf):
AttributeError: 'module' object has no attribute 'AssetShelf'
I0922 18:46:02.055578 11732 device.cpp:32] CUEW initialization succeeded
I0922 18:46:02.055578 11732 device.cpp:34] Found precompiled kernels
I0922 18:46:02.066517 11732 device.cpp:60] HIPEW initialization failed: Error opening HIP dynamic library
Looking in links: c:\Users\ASUS\AppData\Local\Temp\tmp_k9iyfpj
Requirement already satisfied: setuptools in c:\blender game engine\upbge-0.36.1-windows-x86_64\3.6\python\lib\site-packages (63.2.0)
Requirement already satisfied: pip in c:\blender game engine\upbge-0.36.1-windows-x86_64\3.6\python\lib\site-packages (23.0.1)
Requirement already satisfied: uplogic in c:\blender game engine\upbge-0.36.1-windows-x86_64\3.6\python\lib\site-packages (1.9.5)
Requirement already satisfied: setuptools in c:\blender game engine\upbge-0.36.1-windows-x86_64\3.6\python\lib\site-packages (from uplogic) (63.2.0)

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: C:\Blender Game Engine\upbge-0.36.1-windows-x86_64\3.6\python\bin\python.exe -m pip install --upgrade pip
Switching to fully guarded memory allocator.
Blender 3.6.2
Build: 2023-08-19 18:43:57 Windows 
argv[0] = C:\Blender Game Engine\upbge-0.36.1-windows-x86_64\\blender
argv[1] = --debug
argv[2] = --debug-cycles
argv[3] = --python-expr
argv[4] = import bpy; bpy.ops.wm.sysinfo(filepath=r'C:\Users\ASUS\AppData\Local\Temp\blender\debug_logs\blender_system_info.txt')
Read prefs: "C:\Users\ASUS\AppData\Roaming\UPBGE\Blender\3.6\config\userpref.blend"
Debug: 1586, 870
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x0000000010003654
Module  : EZFRD64.DLL
Thread  : 00003598
rcti: : xmin 0, xmax 1585, ymin 95, ymax 964 (1585x869)
Writing: C:\Users\ASUS\AppData\Local\Temp\.blend.crash.txt

**Comment by youle31** [comment]
We can't debug from provided infos. What made you think could come from audio? (because there is 1 case were a special audio configuration can lead to a crash (when there is a soundcard with jack detection on but no audio jack plugged -> there is normally a red cross beside the audio icon in taskbar... jack audio detection can be disabled in realtech audio control panel if it is that)). If it is not related to audio, provided backtrace doesn't help to diagnose the problem.

**Comment by Umuttkrc** [comment]
İ read about people had issues because of audio and i try to fix it but it doesn't fix. I need help because i don't know why my program is crashing.

**Comment by coder-miguel** [comment]
I think I am running into this same issue. Here is the crash file I get:

```
# Blender 3.6.2, Commit date: 2023-08-18 23:50, Hash 191b76bf3e57
File written by newer Blender binary (306.13), expect loss of data!  # Warning
Preferences saved  # Info

# backtrace
Exception Record:

ExceptionCode         : EXCEPTION_ACCESS_VIOLATION
Exception Address     : 0x00007FF795004B44
Exception Module      : blender.exe
Exception Flags       : 0x00000000
Exception Parameters  : 0x2
	Parameters[0] : 0x0000000000000000
	Parameters[1] : 0x0000000000000000


Stack trace:
blender.exe         :0x00007FF794FF9F20  PyInit_aud
blender.exe         :0x00007FF794FF9F20  PyInit_aud
blender.exe         :0x00007FF794FF9F20  PyInit_aud
blender.exe         :0x00007FF791999A00  PyInit_mathutils_noise
blender.exe         :0x00007FF790E20BD0  xmlValidateNotationDecl
blender.exe         :0x00007FF790E20BD0  xmlValidateNotationDecl
blender.exe         :0x00007FF790E20BD0  xmlValidateNotationDecl
blender.exe         :0x00007FF790E20BD0  xmlValidateNotationDecl
blender.exe         :0x00007FF790E20BD0  xmlValidateNotationDecl
blender.exe         :0x00007FF790E20BD0  xmlValidateNotationDecl
blender.exe         :0x00007FF790E20BD0  xmlValidateNotationDecl
blender.exe         :0x00007FF7908D7686  Symbols not available


Loaded Modules :
0x00007FF7907A0000 3.6.2.0              blender.exe  
0x00007FFE0E450000 10.0.22621.3085      ntdll.dll  
0x00007FFE0D1A0000 10.0.22621.3085      KERNEL32.DLL  
0x00007FFE0B790000 10.0.22621.3155      KERNELBASE.dll  
0x00007FFE07E50000 10.0.22621.3085      apphelp.dll  
0x000000006AEC0000 14.3.9505.7000       sysfer.dll  
0x00007FFE0E260000 10.0.22621.2506      USER32.dll  
0x00007FFDF0280000                      tbbmalloc.dll  
0x00007FFE05E10000                      tbb.dll  
0x00007FFE0BE00000 10.0.22621.3085      win32u.dll  
0x00007FFE0D7F0000 10.0.22621.3085      GDI32.dll  
0x00007FFE0BFC0000 10.0.22621.2506      ucrtbase.dll  
0x00007FFE0BEA0000 10.0.22621.3085      gdi32full.dll  
0x00007FFE0BBC0000 10.0.22621.2506      msvcp_win.dll  
0x00007FFE0C720000 10.0.22621.3085      SHELL32.dll  
0x00007FFDCD7B0000 14.29.30139.0        MSVCP140.dll  
0x00007FFE05AB0000 14.29.30139.0        VCRUNTIME140.dll  
0x00007FFE02FE0000 14.29.30139.0        VCRUNTIME140_1.dll  
0x00007FFE0D520000 10.0.22621.1         WS2_32.dll  
0x00007FFE0D5A0000 10.0.22621.2792      RPCRT4.dll  
0x00007FFE0DB50000 10.0.22621.3007      ADVAPI32.dll  
0x00007FFDB72B0000                      OpenImageIO_Util.dll  
0x00007FFD62B50000 4.1.0.0              embree4.dll  
0x00007FFE0E1B0000 7.0.22621.2506       msvcrt.dll  
0x00007FFD62260000                      OpenImageIO.dll  
0x00007FFE0D290000 10.0.22621.3007      sechost.dll  
0x00007FFE0BDD0000 10.0.22621.2506      bcrypt.dll  
0x00007FFE0DC10000 10.0.22621.2506      ole32.dll  
0x00007FFE0DE20000 10.0.22621.3085      combase.dll  
0x00007FFE0D440000 10.0.22621.2506      SHLWAPI.dll  
0x00007FFD61E60000                      OpenColorIO_2_2.dll  
0x00007FFE0D8F0000 10.0.22621.2715      shcore.dll  
0x00007FFDEB780000                      boost_python310-vc142-mt-x64-1_80.dll  
0x00007FFE0D8B0000 10.0.22621.2792      IMM32.dll  
0x00007FFDB79F0000                      epoxy-0.dll  
0x00007FFDEB330000                      Iex.dll  
0x00007FFD5EC20000 10.0.0.0             openvdb.dll  
0x00007FFD603D0000                      usd_ms.dll  
0x00007FFD689E0000                      OpenEXR.dll  
0x00007FFDEB070000                      Imath.dll  
0x00007FFE02FC0000 60.1.100.0           avdevice-60.dll  
0x00007FFD5C4D0000 60.3.100.0           avformat-60.dll  
0x00007FFD5C710000 60.3.100.0           avcodec-60.dll  
0x00007FFE0C1C0000 10.0.22621.2506      OLEAUT32.dll  
0x00007FFD5C310000 58.2.100.0           avutil-58.dll  
0x00007FFDC17D0000 7.1.100.0            swscale-7.dll  
0x00007FFDB5980000 1.21.1.0             OpenAL32.dll  
0x00007FFD5C140000 1.1.0.0              sndfile.dll  
0x00007FFD684D0000 2.0.20.0             SDL2.dll  
0x00007FFE0C2A0000 10.0.22621.2506      SETUPAPI.dll  
0x00007FFD5C020000                      gmp-10.dll  
0x00007FFE022C0000                      libgmpxx.dll  
0x00007FFE02000000                      boost_thread-vc142-mt-x64-1_80.dll  
0x00007FFDC0ED0000                      boost_locale-vc142-mt-x64-1_80.dll  
0x00007FFD5BB50000 3.10.12150.1013      python310.dll  
0x00007FFE022B0000                      tbbmalloc_proxy.dll  
0x00007FFDEB640000 10.0.22621.2506      AVIFIL32.dll  
0x00007FFDD75C0000 6.10.22621.2506      COMCTL32.dll  
0x00007FFE01B50000 10.0.22621.1         VERSION.dll  
0x00007FFD5B770000 6.1.0.0              sycl6.dll  
0x00007FFDBF960000                      OpenEXRCore.dll  
0x00007FFDF2860000 10.0.22621.2506      dbgeng.dll  
0x00007FFE08DF0000 10.0.22621.2506      dbghelp.dll  
0x00007FFE086F0000 10.0.22621.3085      dwmapi.dll  
0x00007FFD688F0000                      fftw3.dll  
0x00007FFD5B670000 10.0.22621.2506      OPENGL32.dll  
0x00007FFDF9820000                      IlmThread.dll  
0x00007FFDBD020000                      MaterialXRender.dll  
0x00007FFDB7EA0000                      MaterialXGenGlsl.dll  
0x00007FFDE9BF0000                      MaterialXFormat.dll  
0x00007FFDB1320000                      MaterialXGenShader.dll  
0x00007FFD5B5A0000                      MaterialXCore.dll  
0x00007FFDED750000 10.0.22621.2506      AVICAP32.dll  
0x00007FFE0A470000 10.0.22621.1         Secur32.dll  
0x00007FFDEB540000 4.10.100.0           swresample-4.dll  
0x00007FFDFE700000 10.0.22621.2506      WINMM.dll  
0x00007FFDEB1C0000 10.0.22621.2506      MSVFW32.dll  
0x00007FFDEB150000 10.0.22621.1         MSACM32.dll  
0x00007FFDF9AB0000 10.0.22621.2506      dbgmodel.dll  
0x00007FFE06450000 10.0.22621.2506      XmlLite.dll  
0x00007FFDD8B20000 10.0.22621.2506      GLU32.dll  
0x00007FFE085A0000 10.0.22621.3085      dxcore.dll  
0x00007FFE0AA40000 10.0.22621.3007      SSPICLI.DLL  
0x00007FFE0B480000 10.0.22621.2506      cfgmgr32.DLL  
0x000002566E450000 7.11.18110.0         umppc18110.dll  
0x00007FFE0A6A0000 10.0.22621.2715      kernel.appcore.dll  
0x00007FFE094D0000 10.0.22621.3085      windows.storage.dll  
0x00007FFE09360000 10.0.22621.2792      wintypes.dll  
0x00007FFE084C0000 10.0.22621.3007      uxtheme.dll  
0x00007FFE0BB40000 10.0.22621.2506      bcryptPrimitives.dll  
0x00007FFE0B6C0000 10.0.22621.2506      profapi.dll  
0x00007FFE0D340000 2001.12.10941.16384  clbcatq.dll  
0x00007FFDFAFC0000 10.0.22621.2506      MMDevApi.dll  
0x00007FFE0B450000 10.0.22621.2506      DEVOBJ.dll  
0x00007FFE0D9F0000 10.0.22621.3085      MSCTF.dll  
0x00007FFE05670000 10.0.22621.3085      directxdatabasehelper.dll  
0x00007FFE02020000 10.0.22621.3155      AppXDeploymentClient.dll  
0x00007FFD588F0000 31.0.15.5168         nvoglv64.dll  
0x00007FFE0A450000 10.0.22621.1         WTSAPI32.dll  
0x00007FFE0B090000 10.0.22621.2506      msasn1.dll  
0x00007FFE015E0000 10.0.22621.1         cryptnet.dll  
0x00007FFE0BC60000 10.0.22621.2506      CRYPT32.dll  
0x00007FFE005F0000 10.0.22621.2506      drvstore.dll  
0x00007FFE00380000 10.0.22621.3085      wldp.dll  
0x00007FFE0B020000 10.0.22621.1         cryptbase.dll  
0x00007FFE0BE30000 10.0.22621.3085      WINTRUST.dll  
0x00007FFE0A800000 10.0.22621.1         ntmarta.dll  
0x00007FFE0C1A0000 10.0.22621.1         imagehlp.dll  
0x00007FFE0B040000 10.0.22621.2506      CRYPTSP.dll  
0x00007FFE0A600000 10.0.22621.1         rsaenh.dll  
0x00007FFD70E10000 31.0.15.5168         nvgpucomp64.dll  
0x00007FFE0AFD0000 10.0.22621.2506      powrprof.dll  
0x00007FFE0AF50000 10.0.22621.1         UMPDC.dll  
0x00007FFE0ACC0000 10.0.22621.2506      WINSTA.dll  
0x00007FFDB0220000 10.0.22621.2506      dataexchange.dll  
0x00007FFE01150000 10.0.22621.3085      twinapi.appcore.dll  
0x00007FFE085E0000 10.0.22621.3085      dxgi.dll  
0x00007FFE072A0000 10.0.22621.2506      d3d11.dll  
0x00007FFDABC30000 31.0.15.5168         nvldumdx.dll  
0x00007FFDF0BE0000 3.12.3354.5005       NvMessageBus.dll  
0x00007FFD50BC0000 31.0.15.5168         nvwgf2umx.dll  
0x00007FFDF1440000 31.0.15.5168         nvapi64.dll  
0x00007FFDFFF70000 31.0.101.4953        igd10iumd64.dll  
0x00007FFDFE740000 31.0.101.4953        igd10um64xe.DLL  
0x00007FFDFDB10000 1.0.171.0            IntelControlLib.dll  
0x00007FFDFD400000 31.0.101.4953        igdgmm64.dll  
0x00007FFDF2F60000 31.0.101.4953        igc64.dll  
0x00007FFE07500000 10.0.22621.3085      dcomp.dll  
0x00007FFE00460000 10.0.22621.3085      textinputframework.dll  
0x00007FFE07B70000 10.0.22621.3085      CoreMessaging.dll  
0x00007FFE042B0000 10.0.22621.2506      CoreUIComponents.dll  
0x00007FFDAD330000 10.0.22621.3085      explorerframe.dll  
0x00007FFDCAC40000 10.0.22621.2506      directmanipulation.dll  
0x00007FFDE9D40000 10.0.22621.1         MPR.dll  
0x00007FFD99A50000 10.0.22621.2506      p9np.dll  
0x00007FFD9A1F0000 10.0.22621.1         drprov.dll  
0x00007FFD99A30000 10.0.22621.2506      ntlanman.dll  
0x00007FFD99A10000 10.0.22621.1         davclnt.dll  
0x00007FFE02C90000 10.0.22621.2506      wkscli.dll  
0x00007FFE01660000 10.0.22621.1         cscapi.dll  
0x00007FFE0A230000 10.0.22621.2506      netutils.dll  
0x00007FFE09DD0000 10.0.22621.1         hid.dll  
0x00007FFDEBBB0000 10.0.22621.1         dinput8.dll  
0x00007FFDCAE50000 10.0.22621.2506      inputhost.dll  
0x00007FFE014B0000 10.0.22621.3085      Windows.Gaming.Input.dll  
0x00007FFE00B20000 10.0.22621.3085      OneCoreUAPCommonProxyStub.dll  
0x00007FFE05F80000 10.0.22621.1         XInput1_4.dll  
0x0000025607080000 3.10.12150.1013      python3.DLL  
0x00007FFD58640000                      _multiarray_umath.cp310-win_amd64.pyd  
0x00007FFDEBAD0000                      _multiarray_tests.cp310-win_amd64.pyd  
0x00007FFDEBAB0000 3.10.12150.1013      _socket.pyd  
0x00007FFE09EF0000 10.0.22621.1         IPHLPAPI.DLL  
0x00007FFE05F70000 3.10.12150.1013      select.pyd  
0x00007FFDEBA80000 3.10.12150.1013      _ctypes.pyd  
0x00007FFDEBBA0000                      libffi-7.dll  
0x00007FFD58430000                      _umath_linalg.cp310-win_amd64.pyd  
0x00007FFDEBA60000                      _pocketfft_internal.cp310-win_amd64.pyd  
0x00007FFDB5B10000                      mtrand.cp310-win_amd64.pyd  
0x00007FFDEBA30000                      bit_generator.cp310-win_amd64.pyd  
0x00007FFDEBA00000                      _common.cp310-win_amd64.pyd  
0x00007FFDEB9F0000 3.10.12150.1013      _hashlib.pyd  
0x00007FFD57EF0000 3.0.9.0              libcrypto-3.dll  
0x00007FFDCD770000                      _bounded_integers.cp310-win_amd64.pyd  
0x00007FFDEB050000                      _mt19937.cp310-win_amd64.pyd  
0x00007FFDCAAA0000                      _philox.cp310-win_amd64.pyd  
0x00007FFDC0390000                      _pcg64.cp310-win_amd64.pyd  
0x00007FFDEB910000                      _sfc64.cp310-win_amd64.pyd  
0x00007FFD57E40000                      _generator.cp310-win_amd64.pyd  
0x00007FFDEB770000 3.10.12150.1013      _queue.pyd  

# Python backtrace
```

The thing with my computer is that windows audio is not enabled because I do not have any audio devices. I have tried every audio setting, including "none" and I get the same crash when trying to start the game.

As a side note, as of this comment, the alpha version of 0.4 is also giving a similar error.
